### PR TITLE
Sf 1073

### PR DESCRIPTION
**Pull request by zoomchik**

### CODE REVIEW

**Comment by zoomchik** [comment]
Linked to https://github.com/groupby/storefront-navigation/pull/57

**Review by Vic-Dev — CHANGES_REQUESTED** [review]
You need use a validator to check whether the navigationId is `orable` (ie, has the field `or: true` on it) before allowing this behaviour. You can't "select all" for `andable` navigations.

**Review by Vic-Dev — CHANGES_REQUESTED** [review]
Needs tests

**Comment by jmbtutor** [comment]
Archiving repo. Closing.

**Pull request closed without merging**
